package maps

import (
	"math/rand"
	"strings"
	"time"
)

func getRandomNHBDInMTL() string {
	neighborhoods := []string{
		"Ahuntsic",
		"Benny Farm",
		"Bois-Franc, Montreal",
		"Cartierville",
		"Centre-Sud",
		"Chinatown, Montreal",
		"Cité du Havre",
		"Cité du Multimédia",
		"Côte-des-Neiges",
		"Côte-Saint-Paul",
		"Downtown Montreal",
		"Faubourg à m'lasse",
		"Faubourg Saint-Laurent",
		"Garment District, Montreal",
		"Gay Village, Montreal",
		"Glenmount, Montreal",
		"Golden Square Mile",
		"Goose Village",
		"Greektown, Montreal",
		"Griffintown",
		"Historic Jewish Quarter, Montreal",
		"Hochelaga-Maisonneuve",
		"Îlot-Trafalgar-Gleneagles",
		"L'Île-Bizard, Quebec",
		"La Petite-Patrie",
		"Little Burgundy",
		"Little Dublin",
		"Little Italy, Montreal",
		"Little Maghreb",
		"Little Portugal, Montreal",
		"Longue-Pointe",
		"Loyola (Montreal)",
		"Milton Park, Montreal",
		"Mercier, Montreal",
		"Mile End, Montreal",
		"Monkland Village",
		"Notre-Dame-de-Grâce",
		"Nouveau-Bordeaux",
		"Nuns' Island",
		"Old Montreal",
		"Overdale",
		"Parc d'entreprises de la Pointe-Saint-Charles",
		"Park Extension",
		"Pierrefonds, Quebec",
		"Pointe-aux-Trembles",
		"Pointe-Saint-Charles",
		"Quad Windsor",
		"Quartier Concordia",
		"Quartier des spectacles",
		"Quartier international de Montréal",
		"Quartier Latin, Montreal",
		"Red-Light District, Montreal",
		"Rivière-des-Prairies, Quebec",
		"Saint-Henri, Montreal",
		"Saint-Michel, Montreal",
		"Sainte-Geneviève, Quebec",
		"Sainte-Marie, Montreal",
		"Sault-au-Récollet",
		"Shaughnessy Village",
		"Snowdon, Montreal",
		"Space for Life",
		"Le Triangle",
		"Turcot, Quebec",
		"Viauville",
		"Ville Saint-Pierre",
		"Ville-Émard",
		"Villeray, Montreal",
		"Windmill Point",
	}

	rand.Seed(time.Now().UnixNano())

	max := len(neighborhoods) - 1

	neighborhood := neighborhoods[rand.Intn(max+1)]

	if strings.Contains(neighborhood, "Montreal") {
		return neighborhood + ", Canada"
	}

	return neighborhood + ", Montreal, Canada"
}

func getRandomNHBInParis() string {
	neighborhoods := []string{
		"Paris Central",
		"8th Arrondissement",
		"9th Arrondissement",
		"10th Arrondissement",
		"11th Arrondissement",
		"12th Arrondissement",
		"16th Arrondissement",
		"17th Arrondissement",
		"18th Arrondissement",
		"19th Arrondissement",
		"20th Arrondissement",
		"5th Arrondissement",
		"6th Arrondissement",
		"7th Arrondissement",
		"13th Arrondissement",
		"14th Arrondissement",
		"15th Arrondissement",
		"Charonne",
		"Montmartre",
		"South Pigalle",
		"Le Marais",
		"Belleville-Menilmontant",
		"Oberkampf",
		"Canal Saint-Martin",
		"Haut Marais",
		"Montorgueil",
		"Batignolles",
		"Bastille",
		"Le Charlotte",
		"COVA Paris",
		"Saint-Germain-des-Prés",
		"Latin Quarter",
		"Montparnasse",
		"Essonne",
		"Paris",
		"Boulogne-Billancourt",
		"Saint-Denis",
		"Argenteuil",
		"Montreuil",
		"Nanterre",
		"Vitry-sur-Seine",
		"Créteil",
		"Asnières-sur-Seine",
		"Versailles",
		"Colombes",
		"Aubervilliers",
		"Aulnay-sous-Bois",
		"Courbevoie",
		"Rueil-Malmaison",
		"Champigny-sur-Marne",
		"Saint-Maur-des-Fossés",
		"Drancy",
		"Issy-les-Moulineaux",
		"Noisy-le-Grand",
		"Levallois-Perret",
		"Cergy",
		"Antony",
		"Neuilly-sur-Seine",
		"Clichy",
		"Ivry-sur-Seine",
		"Sarcelles",
		"Villejuif",
		"Le Blanc-Mesnil",
		"Pantin",
		"Maisons-Alfort",
		"Épinay-sur-Seine",
		"Évry-Courcouronnes",
		"Chelles",
		"Meaux",
		"Fontenay-sous-Bois",
		"Bondy",
		"Clamart",
		"Sartrouville",
		"Bobigny",
		"Sevran",
		"Corbeil-Essonnes",
		"Vincennes",
		"Montrouge",
		"Suresnes",
		"Saint-Ouen-sur-Seine",
		"Massy",
		"Meudon",
		"Puteaux",
		"Mantes-la-Jolie",
		"Rosny-sous-Bois",
		"Gennevilliers",
		"Livry-Gargan",
		"Alfortville",
		"Choisy-le-Roi",
		"Noisy-le-Sec",
		"Garges-lès-Gonesse",
		"La Courneuve",
		"Saint-Germain-en-Laye",
		"Melun",
		"Gagny",
		"Stains",
		"Bagneux",
		"Pontault-Combault",
		"Châtillon",
		"Poissy",
		"Villepinte",
		"Savigny-sur-Orge",
		"Bagnolet",
		"Sainte-Geneviève-des-Bois",
		"Tremblay-en-France",
		"Conflans-Sainte-Honorine",
		"Franconville",
		"Neuilly-sur-Marne",
		"Le Perreux-sur-Marne",
		"Châtenay-Malabry",
		"Montigny-le-Bretonneux",
		"Palaiseau",
		"Athis-Mons",
		"Villeneuve-Saint-Georges",
		"Trappes",
		"Les Mureaux",
		"Houilles",
		"Plaisir",
		"Nogent-sur-Marne",
		"Chatou",
		"Goussainville",
		"Viry-Châtillon",
		"L'Haÿ-les-Roses",
		"Vigneux-sur-Seine",
		"Charenton-le-Pont",
		"Pontoise",
		"Cachan",
		"Savigny-le-Temple",
		"Clichy-sous-Bois",
		"Malakoff",
		"Villemomble",
		"La Garenne-Colombes",
		"Pierrefitte-sur-Seine",
		"Saint-Cloud",
		"Draveil",
		"Le Plessis-Robinson",
		"Thiais",
		"Yerres",
		"Ermont",
		"Bezons",
		"Le Chesnay-Rocquencourt",
		"Villiers-sur-Marne",
		"Grigny",
		"Herblay-sur-Seine",
		"Bois-Colombes",
		"Vanves",
		"Guyancourt",
		"Ris-Orangis",
		"Villiers-le-Bel",
		"Fresnes",
		"Sannois",
		"Bussy-Saint-Georges",
		"Sucy-en-Brie",
		"Villeparisis",
		"Brétigny-sur-Orge",
		"Gonesse",
		"Brunoy",
		"Taverny",
		"Romainville",
		"Montfermeil",
		"Le Kremlin-Bicêtre",
		"Limeil-Brévannes",
		"Élancourt",
		"Rambouillet",
		"Champs-sur-Marne",
		"Les Ulis",
		"Eaubonne",
		"Saint-Ouen-l'Aumône",
		"Villeneuve-la-Garenne",
		"Étampes",
		"Fontenay-aux-Roses",
		"Montgeron",
		"Cormeilles-en-Parisis",
		"Torcy",
		"Maisons-Laffitte",
		"Les Pavillons-sous-Bois",
		"Sèvres",
		"Orly",
		"Roissy-en-Brie",
		"Les Lilas",
		"Saint-Mandé",
		"Combs-la-Ville",
		"Deuil-la-Barre",
		"Longjumeau"}

	rand.Seed(time.Now().UnixNano())

	max := len(neighborhoods) - 1

	neighborhood := neighborhoods[rand.Intn(max+1)]

	return neighborhood + ", Ile-de-France, France"
}

func GetRandomNeighbourhood() string {
	rand.Seed(time.Now().UnixNano())

	nhbs := []string{
		getRandomNHBInParis(),
		getRandomNHBDInMTL(),
	}

	max := len(nhbs) - 1

	return nhbs[rand.Intn(max+1)]
}
